package net.sweet.simple.mod;

public enum Ideas {
    QUARRY_THAT_RUNS_OFF_OF_COAL_AND_PUTS_ITEMS_IN_CHESTS,
    BOOTS_THAT_WEIGH_YOU_DOWN_IN_WATER_AND_LAVA,
    HELMET_THAT_LET_YOU_BREATH_IN_WATER,
    HELMET_THAT_GLOWS_BUT_ATTRACTS_MONSTERS_FROM_FURTHER_AWAY_MAYBE,
    NETHER_ABILITY_TO_GET_TO_THE_END,
    MUSHROOM_ISLAND_VILLAGE,
}
